routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::resources([
    'member' => 'MemberController',
    'product' => 'ProductController',
    'product_category' => 'ProductCategoryController',
    'member_category' => 'MemberCategoryController',
    'promos' => 'PromoController',
    'transaksi' => 'TransaksiController',
    'profil' => 'ProfilController'
]);

app/Member.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Member extends Model
{
    public function categoryRef()
    {
        return $this->belongsTo(MemberCategory::class, 'member_category_id');
    }

    public function pinjam()
    {
        return $this->hasMany(Transaksi::class,'member_id' );
    } 
}

app/Http/Controllers/MemberController.php
<?php

namespace App\Http\Controllers;

use App\Member;
use App\MemberCategory;
use Illuminate\Http\Request;

class MemberController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $members = Member::with('categoryRef')->get();
        return view('member.index', compact('members')); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = MemberCategory::all();
        return view('member.create', compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $member = new Member;
        $member->member_category_id = $request->category;
        $member->full_name = $request->full_name;
        $member->dob = $request->dob;
        $member->address = $request->address;
        $member->gender = $request->gender;
        $barcode = str_replace("-","",$request->dob).substr(str_shuffle('0123456789ABCDEFGHIJKLMNOPQRSTUFWXYZ'),1,3);
        $member->barcode = $barcode;
        $member->save();
        return redirect()->route('member.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Member  $member
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $members = Member::with('pinjam')->findOrFail($id);;
        return view('member.history', compact('members'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Member  $member
     * @return \Illuminate\Http\Response
     */
    public function edit(Member $member)
    {
        $category = MemberCategory::all();
        return view('member.edit', compact('category', 'member'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Member  $member
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Member $member)
    {
        $member->member_category_id = $request->category;
        $member->full_name = $request->full_name;
        $member->dob = $request->dob;
        $member->address = $request->address;
        $member->gender = $request->gender;
        $barcode = str_replace("-","",$request->dob).substr(str_shuffle('0123456789ABCDEFGHIJKLMNOPQRSTUFWXYZ'),1,3);
        $member->barcode = $barcode;
        $member->update();
        return redirect()->route('member.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Member  $member
     * @return \Illuminate\Http\Response
     */
    public function destroy(Member $member)
    {
        $member->delete();
        return redirect()->route('member.index');
    }
}

resources/views/member/create.blade.php
@extends('layouts.template')

@section('content')
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
        <div class="header">
            <h2>Tambah Data Anggota</h2>
        </div>
        <form action="{{ route('member.store') }}" method="post">
            @csrf
        <div class="body">
            <form id="form_validation" method="POST" novalidate="novalidate">
            <div class="form-group form-float">
                <label">Produk Kategori</label>
                <select class="form-control show-tick" name="category" id="category">
                    <option>chose...</option>
                        @foreach ($category as $item)
                        <option value="{{ $item->id }}"> {{ $item->name }}</option>
                        @endforeach
                </select>
                </div>
                <div class="form-group form-float">
                    <div class="form-line">
                        <input type="text" class="form-control" name="full_name" required="" aria-required="true">
                        <label class="form-label">Nama Lengkap</label>
                    </div>
                </div>
                <div class="form-group form-float">
                <div>
                        <label">Tanggal Lahir</label>
                        <input type="date" class="form-control" name="dob" required="" aria-required="true">
                        <div class="form-control show-tick"></div>
                    </div>
                </div>
                <div class="form-group form-float">
                    <div class="form-line">
                        <input type="text" class="form-control" name="address" required="" aria-required="true">
                        <label class="form-label">Alamat</label>
                    </div>
                </div>
                <div class="form-group">
                <label">Gender</label>
                <div class="show-tick"></div>
                    <input type="radio" name="gender" id="gender1" value="pria" class="with-gap">
                    <label for="gender1">Pria</label>

                    <input type="radio" name="gender" id="gender2" value="wanita" class="with-gap">
                    <label for="gender2" class="m-l-20">Wanita</label>
                </div>
                <button class="btn btn-danger waves-effect" type="submit">SIMPAN</button>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/member/edit.blade.php
@extends('layouts.template')

@section('content')
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
        <div class="header">
            <h2>Tambah Data Anggota</h2>
        </div>
        <form action="{{ route('member.update', $member->id) }}" method="post">
            @csrf
            @method('put')
        <div class="body">
            <form id="form_validation" method="POST" novalidate="novalidate">
            <div class="form-group form-float">
                <label">Produk Kategori</label>
                <select class="form-control show-tick" name="category" id="category">
                    <option>chose...</option>
                        @foreach ($category as $item)
                        <option value="{{ $item->id }}" {{ $member->member_category_id == $item->id ? 'selected' : '' }}> {{ $item->name }}</option>
                        @endforeach
                </select>
                </div>
                <div class="form-group form-float">
                    <div class="form-line">
                        <input type="text" class="form-control" name="full_name" required="" aria-required="true" value="{{ $member->full_name }}">
                        <label class="form-label">Nama Lengkap</label>
                    </div>
                </div>
                <div class="form-group form-float">
                <div>
                        <label">Tanggal Lahir</label>
                        <input type="date" class="form-control" name="dob" required="" aria-required="true" value="{{ $member->dob }}">
                        <div class="form-control show-tick"></div>
                    </div>
                </div>
                <div class="form-group form-float">
                    <div class="form-line">
                        <input type="text" class="form-control" name="address" required="" aria-required="true" value="{{ $member->address }}">
                        <label class="form-label">Alamat</label>
                    </div>
                </div>
                <div class="form-group">
                <label">Gender</label>
                <div class="show-tick"></div>
                    <input type="radio" name="gender" id="gender1" value="pria" class="with-gap" {{ $member->gender == 'pria' ? 'checked' : '' }}>
                    <label for="gender1">Pria</label>

                    <input type="radio" name="gender" id="gender2" value="wanita" class="with-gap" {{ $member->gender == 'wanita' ? 'checked' : '' }}>
                    <label for="gender2" class="m-l-20">Wanita</label>
                </div>
                <button class="btn btn-danger waves-effect" type="submit">SIMPAN</button>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/member/history.blade.php
@extends('layouts.template')

@section('content')
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
        <div class="header">
            <h2>
                Histori Perbelanjaan
            </h2>
        </div>
        <div class="body">
            <table id="mainTable" class="table table-striped" style="cursor: pointer;">
                <thead>
                <tr>
                    <th>NO</th>
                    <th>KODE TRANSAKSI</th>
                    <th>NAMA PRODUK</th>
                    <th>JUMLAH</th>
                    <th>DISKON</th>
                    <th>TOTAL</th>
                </tr>
                </thead>
                <tbody>
                    @foreach ($members->pinjam as $i => $item)
                        <tr>
                            <th>{{ $i+1 }}</th>
                            <td>{{ $item->trx_number }}</td>
                            <td>{{ $item->categoryRef->name }}</td>
                            <td>{{ $item->quantity }}</td>
                            <td>Rp.{{ $item->discount }}</td>
                            <td>Rp.{{ $item->total}}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        <input style="position: absolute; display: none;"></div>
    </div>
</div>
@endsection

resources/views/member/index.blade.php
@extends('layouts.template')

@section('content')
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    Data Barang
                </h2>
                <ul class="header-dropdown m-r--5">
                <li>
                    <a href="{{ route('member.create') }}" >
                        <button type="button" class="btn btn-danger btn-sm">Tambah</button>
                    </a>
                 </li>
                </ul>
            </div>
            <div class="body table-responsive">
                <table class="table table-condensed">
                    <thead>
                        <tr class="bg-deep-orange">
                            <th>NO</th>
                            <th>Kategori</th>
                            <th>NAMA</th>
                            <th>TANGGAL LAHIR</th>
                            <th>ALAMAT</th>
                            <th>GENDER</th>
                            <th>KODE MEMBER</th>
                            <th>PILIHAN</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($members as $i => $item)
                            <tr class="bg-danger">
                                <th>{{ $i+1 }}</th>
                                <td>{{ $item->categoryRef->name }}</td>
                                <td>{{ $item->full_name }}</td>
                                <td>{{ $item->dob }}</td>
                                <td>{{ $item->address }}</td>
                                <td>{{ $item->gender }}</td>
                                <td>{{ $item->barcode }}</td>
                                <td>
                                    <form action="{{ route ('member.destroy',$item->id) }} " method="post">
                                        <a href="{{ route ('member.edit', $item->id) }}">
                                            <button type="button" class="btn btn-success">Ubah</button>
                                        </a>
                                        @csrf 
                                        @method('delete')
                                            <button type="submit" class="btn btn-danger" 
                                            onclick="return confirm('Yakin Dihapus?' )">Hapus</button>
                                            <a href="{{route('member.show', $item->id) }}">
                                                <button type="button" class="btn btn-primary">Detail</button>
                                            </a>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@endsection